spring:
  application:
    name: singular-point

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.singularpoint.ui

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn

---
# 生产环境
spring:
  profiles:
    active: pro

---
# 开发环境
spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

knife4j:
  enable: true