spring:
  application:
    name: singular-point

server:
  port: 8080

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.singularpoint.ui

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn

mybatis:
  type-aliases-package: org.example.singularpoint.infra.mapper  # mapper接口类位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #xml-sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    ro                                                                                                                                                                                                                                     ot: info
    # 输出 SQL
    druid.sql.Statement: debug
    # 输出查询结果
    druid.sql.ResultSet: debug


---
# 生产环境
spring:
  profiles:
    active: pro


---
# 开发环境
spring:
  profiles:
    active: dev
  datasource:
    # 默认数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/singular_point?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    # 配置数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置数据库连接监控
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: password
        reset-enable: true
        url-pattern: "/druid/*"
        # 访问IP白名单
        allow: 127.0.0.1
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      # 开启拦截监控
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

knife4j:
  enable: true